.TH "src/utils Directory Reference" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBenv\&.cpp\fP"
.br
.ti -1c
.RI "file \fBos\-detect\&.cpp\fP"
.br
.in -1c
