.TH "src/include/utils Directory Reference" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfile\&.h\fP"
.br
.ti -1c
.RI "file \fBenv\&.h\fP"
.br
.ti -1c
.RI "file \fBmisc\&.h\fP"
.br
.ti -1c
.RI "file \fBos\-detect\&.h\fP"
.br
.in -1c
