.TH "src/include/curl_cpp/cppcurl.h" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/curl_cpp/cppcurl.h
.SH SYNOPSIS
.br
.PP
\fR#include <curl/curl\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcppcurl::CPPCURL\fP"
.br
.RI "A simple wrapper for libcurl\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcppcurl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
