.TH "src/curl_cpp/cppcurl.cpp" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/curl_cpp/cppcurl.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'curl_cpp/cppcurl\&.h'\fP
.br
\fR#include <curl/curl\&.h>\fP
.br
\fR#include <curl/easy\&.h>\fP
.br
\fR#include <tlog\&.h>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <memory>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcppcurl\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBcppcurl::WriteCallback\fP (void *contents, size_t size, size_t nmemb, void *userp) \-> size_t"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
