.TH "cppcurl" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cppcurl
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCPPCURL\fP"
.br
.RI "A simple wrapper for libcurl\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBWriteCallback\fP (void *contents, size_t size, size_t nmemb, void *userp) \-> size_t"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto cppcurl::WriteCallback (void * contents, size_t size, size_t nmemb, void * userp) \-> size_t "

.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
