.TH "src/core/github.cpp" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/github.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <sys/wait\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include 'core/pack_core\&.h'\fP
.br
\fR#include 'curl_cpp/cppcurl\&.h'\fP
.br
\fR#include 'json\&.hpp'\fP
.br
\fR#include 'tlog\&.h'\fP
.br
\fR#include 'utils/env\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBinstall_github\fP (std::string url, const std::string_view name, const std::string_view pack_name, const bool vmode) \-> std::string"
.br
.RI "handling GitHub release links "
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto install_github (std::string url, std::string_view name, std::string_view pack_name, const bool vmode) \->  std::string\fR [nodiscard]\fP"

.PP
handling GitHub release links 
.PP
\fBParameters\fP
.RS 4
\fI`url`\fP The home page of the website where the program is hosted 
.br
\fI`name`\fP Name of the software 
.br
\fI`pack_name`\fP Name of the package to download, e\&.g\&. \fRfastfetch-linux-amd64\&.deb\fP 
.br
\fI`vmode`\fP Whether to output more information (for debugging purposes) 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a bool indicating whether the function was executed correctly\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
