.TH "src/main.cpp" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <sys/types\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <argparse/argparse\&.hpp>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br
\fR#include 'log\&.h'\fP
.br
\fR#include 'pack_core\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBmain\fP (int argc, char *argv[]) \-> int"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto main (int argc, char * argv[]) \-> int "

.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
