.TH "src/include/utils/misc.h" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/utils/misc.h
.SH SYNOPSIS
.br
.PP
\fR#include <string_view>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr std::string_view \fBVERSION\fP = '1\&.0'"
.br
.ti -1c
.RI "constexpr std::string_view \fBPACK_NAME\fP = 'releasebutler'"
.br
.ti -1c
.RI "constexpr std::string_view \fBRB_MES_PREV\fP = 'releasebutler: '"
.br
.ti -1c
.RI "constexpr std::string_view \fBRB_DES\fP = 'releasebutler: package manager on GitHub\&.'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::string_view PACK_NAME = 'releasebutler'\fR [constexpr]\fP"

.SS "std::string_view RB_DES = 'releasebutler: package manager on GitHub\&.'\fR [constexpr]\fP"

.SS "std::string_view RB_MES_PREV = 'releasebutler: '\fR [constexpr]\fP"

.SS "std::string_view VERSION = '1\&.0'\fR [constexpr]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
