.TH "src/include/utils/os-detect.h" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/utils/os-detect.h
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <cstdint>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <string_view>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBos_detect\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBos_detect::packinfo\fP"
.br
.RI "Linux distribution related information\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBos_detect::OS_KIND\fP : std::uint8_t { \fBos_detect::debian\fP, \fBos_detect::ubuntu\fP, \fBos_detect::fedora\fP, \fBos_detect::deepin\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBos_detect::OsDetect\fP (const bool vmode) \-> std::optional< enum \fBOS_KIND\fP >"
.br
.RI "Used to detect the current Linux distributions\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr int \fBos_detect::OS_KIND\fP = 4"
.br
.RI "The types of Linux distributions that the current software can detect\&. "
.ti -1c
.RI "constexpr std::array< \fBpackinfo\fP, \fBOS_KIND\fP > \fBos_detect::OS_PACKAGE\fP"
.br
.RI "Information about currently supported Linux distributions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
