.TH "src/utils/os-detect.cpp" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/os-detect.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'utils/os\-detect\&.h'\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <optional>\fP
.br
\fR#include <utility>\fP
.br
\fR#include <tlog\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBos_detect\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBos_detect::OsDetect\fP (const bool vmode) \-> std::optional< enum \fBOS_KIND\fP >"
.br
.RI "Used to detect the current Linux distributions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
