.TH "src/core/pack_core.cpp" 3 "Version 1.0" "ReleaseButler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/pack_core.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'core/pack_core\&.h'\fP
.br
\fR#include <sys/wait\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <openssl/sha\&.h>\fP
.br
\fR#include <array>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <filesystem>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <string_view>\fP
.br
\fR#include 'tlog\&.h'\fP
.br
\fR#include 'utils/confile\&.h'\fP
.br
\fR#include 'utils/misc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBinstall\fP (std::string_view url, std::string_view name, std::string_view pack_name, std::optional< std::string_view > sha256_val, const bool vmode, const bool install) \-> bool"
.br
.RI "Programs for download and installation\&. "
.ti -1c
.RI "auto \fBinstall_core\fP (std::string_view pack_name, const bool vmode) \-> bool"
.br
.RI "Core functions that implement the installation functionality\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto install (std::string_view url, std::string_view name, std::string_view pack_name, std::optional< std::string_view > sha256_val, bool vmode, bool install) \->  bool\fR [nodiscard]\fP"

.PP
Programs for download and installation\&. But in fact \fR\fBinstall()\fP\fP does not perform all of the functions involved in installation that are permitted by the software's operation\&. It's the parsing of the file that implements all of the features allowed for installation\&.

.PP
\fBParameters\fP
.RS 4
\fI`url`\fP The home page of the website where the program is hosted 
.br
\fI`name`\fP Name of the software 
.br
\fI`pack_name`\fP Name of the package to download, e\&.g\&. \fRfastfetch-linux-amd64\&.deb\fP 
.br
\fI`sha256_val`\fP SHA256 of the file to download\&. 
.br
\fI`vmode`\fP Whether to output more information (for debugging purposes) 
.br
\fI`install`\fP Whether to call the corresponding package manager to install after download 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a bool indicating whether the function was executed correctly\&. 
.RE
.PP

.SS "auto install_core (std::string_view pack_name, bool vmode) \->  bool\fR [nodiscard]\fP"

.PP
Core functions that implement the installation functionality\&. 
.PP
\fBParameters\fP
.RS 4
\fI`pack_name`\fP Name of the package to download, e\&.g\&. \fRfastfetch-linux-amd64\&.deb\fP 
.br
\fI`vmode`\fP Whether to output more information (for debugging purposes) 
.RE
.PP
\fBReturns\fP
.RS 4
Returns a bool indicating whether the function was executed correctly\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ReleaseButler from the source code\&.
